version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cryptofolio-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=cryptofolio
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: cryptofolio-redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: