spring:
  application:
    name: cryptofolio-manager

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

  mongodb:
    uri: mongodb://localhost:27017/cryptofolio
    auto-index-creation: true

cryptofolio:
  client:
    coingecko:
      url: https://api.coingecko.com/api/v3
      key: ${COINGECKO_API_KEY}